name: Run Tests on BrowserStack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'which environment to deploy to'
        required: true
        default: 'production'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'BrowserStack env setup'
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: BrowserStack Local tunnel setup
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: set up apache maven
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Run selenium Tests
        run: mvn clean test -P browserstack

      - name: BrowserStack local stop
        uses: browserstack/github-actions/setup-local@master
        with:
          local-tetsing: stop

      - name: Load Test Report History
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build allure test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results   # default folder for maven

      - name: Publish Test Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history