# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Web Automation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'which environment to deploy to'
        required: true
        default: 'production'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: set up apache maven
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'maven'

    - name: Run selenium Tests
      run: mvn clean test -P localExecution

    - name: Load Test Report History
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: localBranch
        path: localBranch

    - name: Build allure test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: localBranch
        allure_history: allure-history
        allure_results: target/allure-results   # default folder for maven

    - name: Publish Test Report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: localBranch
        publish_dir: allure-history

    
