# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Web Automation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'which environment to deploy to'
        required: true
        default: 'production'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Run selenium Tests
      run: mvn clean test -P localExecution
    
